services:
  celestia-init:
    image: ghcr.io/celestiaorg/celestia-app-standalone:02ff9af
    container_name: celestia-init
    entrypoint: /scripts/init.sh
    volumes:
      - ./scripts/init-celestia.sh:/scripts/init.sh:ro
      - celestia-app:/home/celestia/.celestia-appd
    restart: "no"

  celestia-validator:
    image: ghcr.io/celestiaorg/celestia-app-standalone:02ff9af
    container_name: celestia-validator
    ports:
      - "26656:26656"
      - "26657:26657"
      - "9090:9090"
    healthcheck:
      test: [
        "CMD-SHELL",
        "bh=$(curl -sf http://localhost:26657/status | jq -r '.result.sync_info.latest_block_height'); if [ \"$$bh\" -ge 1 ]; then exit 0; else exit 1; fi"
      ]
      interval: 30s
      timeout: 5s
      start_period: 10s
    volumes:
      - celestia-app:/home/celestia/.celestia-appd
    command: >
      start --force-no-bbr
    depends_on:
      celestia-init:
        condition: service_completed_successfully
    networks:
      - celestia-zkevm-net

volumes:
  celestia-app:

networks:
  celestia-zkevm-net:
    driver: bridge