// @generated
// This file is @generated by prost-build.
/// QueryIsmsRequest ...
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryIsmsRequest {
    /// pagination defines an optional pagination for the request.
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::super::super::cosmos::base::query::v1beta1::PageRequest>,
}
/// QueryIsmsResponse ...
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryIsmsResponse {
    #[prost(message, repeated, tag="1")]
    pub isms: ::prost::alloc::vec::Vec<::prost_types::Any>,
    /// pagination defines the pagination in the response.
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::super::super::cosmos::base::query::v1beta1::PageResponse>,
}
/// QueryIsmRequest ...
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryIsmRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
/// QueryIsmResponse ...
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryIsmResponse {
    #[prost(message, optional, tag="1")]
    pub ism: ::core::option::Option<::prost_types::Any>,
}
/// MsgCreateNoopIsm ...
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgCreateNoopIsm {
    /// creator is the message sender.
    #[prost(string, tag="1")]
    pub creator: ::prost::alloc::string::String,
}
/// MsgCreateNoopIsmResponse ...
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgCreateNoopIsmResponse {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
/// MsgCreateAggregationIsm ...
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgCreateAggregationIsm {
    /// creator ...
    #[prost(string, tag="1")]
    pub creator: ::prost::alloc::string::String,
    /// modules - list of ISM IDs to aggregate
    #[prost(string, repeated, tag="2")]
    pub modules: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// threshold - number of ISMs that must pass verification
    #[prost(uint32, tag="3")]
    pub threshold: u32,
}
/// MsgCreateAggregationIsmResponse ...
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgCreateAggregationIsmResponse {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
/// Route
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Route {
    /// ism ...
    #[prost(string, tag="1")]
    pub ism: ::prost::alloc::string::String,
    /// domain ...
    #[prost(uint32, tag="2")]
    pub domain: u32,
}
/// AggregationISM ...
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AggregationIsm {
    /// id ...
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// owner ...
    #[prost(string, tag="2")]
    pub owner: ::prost::alloc::string::String,
    /// modules - list of ISM IDs to aggregate
    #[prost(string, repeated, tag="3")]
    pub modules: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// threshold - number of ISMs that must pass verification
    #[prost(uint32, tag="4")]
    pub threshold: u32,
}
/// NoopISM ...
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NoopIsm {
    /// id ...
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// owner ...
    #[prost(string, tag="2")]
    pub owner: ::prost::alloc::string::String,
}
include!("hyperlane.core.interchain_security.v1.tonic.rs");
// @@protoc_insertion_point(module)