[package]
name = "hyp-cli"
version = "0.1.0"
edition = "2021"

[lib]
name = "hyp_cli"
path = "src/lib.rs"

[[bin]]
name = "hyp-cli"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
celestia-grpc-client = { path = "../celestia-grpc-client" }
celestia-rpc = { workspace = true }
celestia-types = { workspace = true }
clap = { version = "4", features = ["derive"] }
dirs = { workspace = true }
dotenvy = { workspace = true }
ev-types = { workspace = true, features = ["grpc"] }
hex = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_yaml = "0.9"
sp1-sdk = { workspace = true }
tokio = { version = "1", features = ["full"] }
tonic = { version = "0.10", features = ["transport"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[build-dependencies]
sp1-build = { workspace = true }
