// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{EV_COMBINED_ELF, EV_COMBINED_ID};
use risc0_zkvm::{default_prover, ExecutorEnv};

fn main() {}
